name: Task
description: A technical task, chore, or internal improvement
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Describe a technical task that needs to be done (refactoring, CI changes, dependency updates, etc.).

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why?
    validations:
      required: true

  - type: textarea
    id: done-criteria
    attributes:
      label: Done when
      description: How do we know this task is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Affected area
      description: Which part of the project would this touch?
      multiple: true
      options:
        - Core (auction, OpenRTB, APS, mediation, rendering)
        - Adapter — Fastly
        - Adapter — Cloudflare
        - Adapter — Axum
        - Documentation
        - CI / Tooling
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Related issues, dependencies, or notes.
